In [2]:
import pandas as pd
import numpy as np

In [5]:
a=np.array([1,2,3,4])

In [6]:
a

array([1, 2, 3, 4])

In [8]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,5,4,2]])

In [9]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 5, 4, 2]])

In [10]:
a[0]

array([1, 2, 3, 4])

In [11]:
a[1,2]

7

In [12]:
a[[1,2]]

array([[5, 6, 7, 8],
       [9, 5, 4, 2]])

In [13]:
# ARRAY ATTRIBUTES

a.shape

(3, 4)

In [16]:
a.size

12

In [17]:
a.dtype

dtype('int32')

In [18]:
# ARRAY INITIALIZATION

np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.empty((2,4))

array([[4.67296746e-307, 1.69121096e-306, 3.11522054e-307,
        1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.42419530e-306]])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
r=np.arange(12)
re=r.reshape([3,4])

In [34]:
re

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
print(r[3:9])

[3 4 5 6 7 8]


In [45]:
r[3:9]

array([3, 4, 5, 6, 7, 8])

In [51]:
re[1,3]

7

In [52]:
re[1,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [54]:
a1=np.array([1,2,3,4])
a2=np.array([11,12,13,14])
a1+a2

array([12, 14, 16, 18])

In [55]:
a1-a2

array([-10, -10, -10, -10])

In [56]:
a1*a2

array([11, 24, 39, 56])

In [57]:
a1/a2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429])

In [58]:
a1**a2

array([        1,      4096,   1594323, 268435456])

In [59]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [60]:
np.sqrt(a2)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [61]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [62]:
np.exp(a2)

array([  59874.1417152 ,  162754.791419  ,  442413.39200892,
       1202604.28416478])

In [63]:
np.sum(a1)

10

In [64]:
np.sum(a2)

50

In [65]:
np.sum(a1)+np.sum(a2)

60

In [66]:
np.diff(a2)

array([1, 1, 1])

In [67]:
np.prod(a2)

24024

In [68]:
np.mean(a2)

12.5

In [69]:
np.median(a2)

12.5

In [71]:
np.std(a2)

1.118033988749895

In [72]:
np.std(a1)

1.118033988749895

In [73]:
np.min(a2)

11

In [74]:
np.max(a2)

14

In [75]:
arr=np.array([1,2,4])
print(arr+10)

[11 12 14]


In [78]:
np.random.rand(2,3)

array([[0.06468109, 0.6839472 , 0.84137882],
       [0.35875235, 0.33074256, 0.21234636]])

In [79]:
np.random.randint(1,10,size=(3,3))

array([[9, 1, 6],
       [9, 9, 9],
       [1, 3, 4]])

In [80]:
np.random.normal(1,10,size=(3,3))

array([[  1.69538726,  13.66313937,   0.54768662],
       [  0.61451475,   7.05141106, -12.35085846],
       [-18.45997879,  -1.55052095, -12.74023365]])

In [83]:
np.sort([1,5,9,3,7,2,9,6])

array([1, 2, 3, 5, 6, 7, 9, 9])

In [84]:
arr.ndim

1

In [85]:
np.add([1, 2], [3, 4])


array([4, 6])

In [86]:
np.subtract([3, 4], [1, 2])


array([2, 2])

In [87]:
np.multiply([1, 2], [3, 4])


array([3, 8])

In [88]:
np.divide([4, 6], [2, 3])


array([2., 2.])

Aggregate Functions Σ

In [89]:
np.sum([1, 2, 3])


6

In [90]:
np.mean([1, 2, 3])


2.0

In [91]:
np.median([1, 2, 3])


2.0

In [92]:
np.std([1, 2, 3])


0.816496580927726

In [93]:
np.var([1, 2, 3])


0.6666666666666666

Array Manipulation 🔄

In [94]:
np.reshape([1, 2, 3, 4], (2, 2))


array([[1, 2],
       [3, 4]])

In [95]:
np.array([[1, 2], [3, 4]]).flatten()


array([1, 2, 3, 4])

In [96]:
np.transpose([[1, 2], [3, 4]])


array([[1, 3],
       [2, 4]])

Statistical Functions 📊

In [97]:
np.min([1, 2, 3])


1

In [98]:
np.max([1, 2, 3])


3

In [99]:
np.percentile([1, 2, 3, 4], 50)


2.5

Random Number Generation 🎲

In [100]:
np.random.rand(3, 2)
# np.random.rand(): Generates random numbers from a uniform distribution

array([[0.83899706, 0.59858666],
       [0.18676673, 0.49914587],
       [0.41355641, 0.980037  ]])

In [101]:
# np.random.randn(): Generates random numbers from a normal distribution.

np.random.randn(3, 2)

array([[-0.79399126,  0.12494169],
       [ 0.76110011, -1.13221242],
       [ 1.32173601, -1.17429716]])

In [102]:
# np.random.randint(): Generates random integers within a specified range.

np.random.randint(1, 10, 5)

array([4, 7, 8, 7, 2])

Linear Algebra ➕

In [103]:
# Computes the dot product of two arrays
np.dot([1, 2], [3, 4])

11

In [104]:
# Matrix product of two arrays
np.matmul([[1, 2], [3, 4]], [[5, 6], [7, 8]])

array([[19, 22],
       [43, 50]])

In [105]:
# Computes the inverse of a matrix
np.linalg.inv([[1, 2], [3, 4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [106]:
# Computes the eigenvalues and eigenvectors
np.linalg.eig([[1, 2], [3, 4]])

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [107]:
import numpy as np

# Array creation
a = np.array([1, 2, 3])
b = np.ones((2, 3))

# Basic operations
c = np.add(a, [4, 5, 6])

# Aggregate functions
sum_a = np.sum(a)
mean_a = np.mean(a)

# Array manipulation
reshaped_b = b.reshape(3, 2)
flattened_b = b.flatten()

# Statistical functions
min_a = np.min(a)
percentile_a = np.percentile(a, 50)

# Random number generation
random_array = np.random.rand(2, 2)

# Linear algebra
dot_product = np.dot([1, 2], [3, 4])
matrix_product = np.matmul([[1, 2], [3, 4]], [[5, 6], [7, 8]])

print("Array a:", a)
print("Array b:", b)
print("Added array c:", c)
print("Sum of a:", sum_a)
print("Mean of a:", mean_a)
print("Reshaped b:", reshaped_b)
print("Flattened b:", flattened_b)
print("Minimum of a:", min_a)
print("50th percentile of a:", percentile_a)
print("Random array:", random_array)
print("Dot product:", dot_product)
print("Matrix product:", matrix_product)


Array a: [1 2 3]
Array b: [[1. 1. 1.]
 [1. 1. 1.]]
Added array c: [5 7 9]
Sum of a: 6
Mean of a: 2.0
Reshaped b: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Flattened b: [1. 1. 1. 1. 1. 1.]
Minimum of a: 1
50th percentile of a: 2.0
Random array: [[0.64504541 0.2825352 ]
 [0.88938133 0.01704023]]
Dot product: 11
Matrix product: [[19 22]
 [43 50]]


In [109]:
# Array Creation
np.empty((2, 3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [112]:
# Creates an identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
# Creates an array filled with a specified value
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [113]:
# Array Manipulation 
np.concatenate(([1, 2], [3, 4]))


array([1, 2, 3, 4])

In [114]:
np.stack(([1, 2], [3, 4]))


array([[1, 2],
       [3, 4]])

In [117]:
np.hstack(([1, 2], [3, 4]))


array([1, 2, 3, 4])

In [118]:
np.vstack(([1, 2], [3, 4]))


array([[1, 2],
       [3, 4]])

Mathematical Functions 

In [119]:
np.exp([1, 2, 3])


array([ 2.71828183,  7.3890561 , 20.08553692])

In [120]:
np.log([1, 2, 3])


array([0.        , 0.69314718, 1.09861229])

In [121]:
np.log10([1, 10, 100])


array([0., 1., 2.])

In [122]:
np.sqrt([1, 4, 9])


array([1., 2., 3.])

In [123]:
np.sin([0, np.pi/2, np.pi])


array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [126]:
# Advanced Indexing and Slicing
np.take([1, 2, 3, 4], [0, 2])

array([1, 3])

In [127]:
a = np.array([1, 2, 3, 4])
np.put(a, [0, 2], [5, 6])


In [128]:
# Set Operations
np.unique([1, 2, 2, 3, 3, 3])


array([1, 2, 3])

In [129]:
np.intersect1d([1, 2, 3], [2, 3, 4])


array([2, 3])

In [130]:
np.union1d([1, 2, 3], [2, 3, 4])


array([1, 2, 3, 4])

In [131]:
np.setdiff1d([1, 2, 3], [2, 3, 4])


array([1])

In [132]:
np.in1d([1, 2, 3], [2, 3, 4])
# Tests whether each element of an array is in another array

array([False,  True,  True])

In [136]:
# String Operations
np.char.add(['hello', 'world'], ['!', '!'])


array(['hello!', 'world!'], dtype='<U6')

In [137]:
np.char.multiply(['hello', 'world'], 3)


array(['hellohellohello', 'worldworldworld'], dtype='<U15')

In [138]:
np.char.center(['hello', 'world'], 10, fillchar='*')


array(['**hello***', '**world***'], dtype='<U10')

In [139]:
np.char.capitalize(['hello', 'world'])



array(['Hello', 'World'], dtype='<U5')

In [140]:
np.char.lower(['HELLO'])

array(['hello'], dtype='<U5')